package GUIStuff;

import GUIStuff.MainWindow;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;

/**
 * Created by Lach on 2016-12-07.
 */
public class CreateNewBreederForm implements Runnable {
    private JButton OKButton;
    private JButton ANULUJButton;
    private JTextField textField1;
    //private JTextField textField2;
    //private JTextField textField3;
    private JPanel nazw;
    private MainWindow source;
    private JFrame fata;

    public CreateNewBreederForm(MainWindow nSource) {
        ActionListener fajny = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (e.getSource() == OKButton) {
                    source.CreateBreederFromForm(textField1.getText());//,textField3.getText(),textField2.getText());
                } else {
                    fata.dispatchEvent(new WindowEvent(fata, WindowEvent.WINDOW_CLOSING));
                }
            }
        };
        OKButton.addActionListener(fajny);
        ANULUJButton.addActionListener(fajny);
        source = nSource;
    }

    public void run() {
        JFrame frame = new JFrame("CreateNewBreederForm");
        frame.setContentPane(this.nazw);
        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        fata = frame;
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        nazw = new JPanel();
        nazw.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        OKButton = new JButton();
        OKButton.setText("OK");
        nazw.add(OKButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ANULUJButton = new JButton();
        ANULUJButton.setText("ANULUJ");
        nazw.add(ANULUJButton, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textField1 = new JTextField();
        textField1.setText("");
        nazw.add(textField1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("ilosc genotypow");
        nazw.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return nazw;
    }
}
